Models/Movie.cs
using System.Text.Json;

namespace TheWatchlist.Models
{
    public class Movie
    {
        public string? Title { get; set; }
        public string? Year { get; set; }
        public string? Rated { get; set; }
        public string? Released { get; set; }
        public string? Runtime { get; set; }
        public string? Genre { get; set; }
        public string? Director { get; set; }
        public string? Writer { get; set; }
        public string? Actors { get; set; }
        public string? Plot { get; set; }
        public string? Language { get; set; }
        public string? Country { get; set; }
        public string? Awards { get; set; }
        public string? Poster { get; set; }
        public string? Metascore { get; set; }
        public string? imdbRating { get; set; }
        public string? imdbVotes { get; set; }
        public string? imdbID { get; set; }
        public string? Type { get; set; }
        public string? DVD { get; set; }
        public string? BoxOffice { get; set; }
        public string? Production { get; set; }
        public string? Website { get; set; }
        public string? Response { get; set; }
        public bool Seen { get; set; } = false;
        public override string ToString() => JsonSerializer.Serialize<Movie>(this);
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TheWatchlist.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWatchlist.Models;
using TheWatchlist.Services;

namespace TheWatchlist.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public JsonFileService MovieService;
        public IEnumerable<Movie> Movies { get; private set; }
        public IEnumerable<Movie> SearchedMovie { get; private set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public IndexModel(ILogger<IndexModel> logger, JsonFileService movieService)
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            _logger = logger;
            MovieService = movieService;
        }

        public async Task OnGetAsync()
        {
            MovieService.DeleteSearchedMovie();
            Movies = MovieService.GetMovies();
            if (!string.IsNullOrEmpty(SearchString))
            {
                await JsonFileService.SearchMovie(SearchString);
                await Task.Delay(200);
                SearchedMovie = MovieService.GetSearchedMovie();
            }
        }
        public void OnPostSeen()
        {
                var seen = Request.Form["Seen"];
                MovieService.SeenMovie(seen);
                Movies = MovieService.GetMovies(); 
        }
        public void OnPostDelete()
        {
            var delete = Request.Form["Delete"];
            MovieService.DeleteMovie(delete);
            Movies = MovieService.GetMovies();
        }
        public void OnPostAddToWatchList()
        {
            MovieService.AddSearchedMovie();
            Movies = MovieService.GetMovies();
        }
    }
}

Pages/Movies/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWatchlist.Models;
using TheWatchlist.Services;

namespace TheWatchlist.Pages.Movies
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public JsonFileService MovieService;
        public IEnumerable<Movie> Movie { get; private set; }

        [BindProperty(SupportsGet = true)]
        public string ? SearchString { get; set; }

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public IndexModel(ILogger<IndexModel> logger, JsonFileService movieService)
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            _logger = logger;
            MovieService = movieService;
        }
        public async Task OnGetAsync()
        {
            if (!string.IsNullOrEmpty(SearchString))
            {
                await JsonFileService.SearchMovie(SearchString);
            }
            await Task.Delay(200);
            try
            {
                Movie = MovieService.GetSearchedMovie();
            }
            catch
            {
                Movie = MovieService.GetMovies();
            }
            
        }
        public void OnPost()
        {
            MovieService.AddSearchedMovie();
            Movie = MovieService.GetSearchedMovie();
        }
    }
}

Pages/Movies/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWatchlist.Models;
using TheWatchlist.Services;

namespace TheWatchlist.Pages.Movies
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public JsonFileService MovieService;
        public IEnumerable<Movie> Movies { get; private set; }

        [BindProperty(SupportsGet = true)]
        public string ? SearchString { get; set; }

        public IndexModel(ILogger<IndexModel> logger, JsonFileService movieService)
        {
            _logger = logger;
            MovieService = movieService;
        }
        public async Task OnGetAsync()
        {
            //Movies = MovieService.GetMovies();
            if (!string.IsNullOrEmpty(SearchString))
            {
                await JsonFileService.SearchMovie(SearchString);
            }
        }
        public void OnPost()
        {
            MovieService.AddSearchedMovie();
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheWatchlist.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}
<script src="https://kit.fontawesome.com/8cafc277ac.js" crossorigin="anonymous"></script>

<div class="container center">
	<p>
	<form method="get" class="search-bar">
			<input type="text" asp-for="SearchString" placeholder="Search for a movie..." />
			<button type="submit"><img src="~/images/searchicon.png"></button>
	</form>
	</p>
</div>

@try 
{
	@foreach (var item in Model.SearchedMovie)
	{
		<div class="center">
		<div class="moviecard">
			<div class="moviecard-poster">
				<img src="@item.Poster" alt="@item.Title">
			</div>
			<div class="moviecard-body">
				<span class="moviecard-title">@item.Title</span>
				<p>
					<span>@item.Year</span>
					<span>@item.Runtime</span>
					<span>@item.Genre</span>
				</p>
				<p>
					<span>IMDB: @item.imdbRating</span>
					<span>Metascore: @item.Metascore</span>
				</p>
				<p class="moviecard-plot">
					@item.Plot
				</p>
				<div class="moviecard-buttons">
					<form method="post">
						<input type="submit" class="btn btn-secondary" value="Add to Watchlist" asp-page-handler="AddToWatchlist" />
					</form>
				</div>
				</div>
		</div>
		</div>
	}
}		
catch
{
	@foreach (var item in Model.Movies)
	{
		<div class="center">
		<div class="moviecard">
			<div class="moviecard-poster">
				<img src="@item.Poster" alt="@item.Title">
			</div>
			<div class="moviecard-body">
				<span class="moviecard-title">@item.Title</span>
				<p>
					<span>@item.Year</span>
					<span>@item.Runtime</span>
					<span>@item.Genre</span>
				</p>
				<p>
					<span>IMDB: @item.imdbRating</span>
					<span>Metascore: @item.Metascore</span>
				</p>
				<p class="moviecard-plot">
					@item.Plot
				</p>
				<div class="moviecard-buttons">
				@if (item.Seen == true)
				{
					<form method="post">
						<button class="btn btn-success" id="@item.Title" type="submit" name="Seen" value="@item.Title" asp-page-handler="Seen">Seen</button>
					</form>
				}
				else
				{
					<form method="post">
						<button class="btn btn-secondary" id="toggleseen" type="submit" name="Seen" value="@item.Title" asp-page-handler="Seen">Mark as seen</button>
					</form>
				}
				<form method="post">
					<button class="btn btn-danger" id="delete" type="submit" name="Delete" value="@item.Title" asp-page-handler="Delete">Delete</button>
				</form>
				</div>
			</div>
		</div>
		</div>
	}
}

Pages/Movies/Add.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Search";
}

<div class="container-lg">
    <h2 class="text-light">Search for a movie</h2>
    <form method="get">
        <p>
            <input type="text" asp-for="SearchString" />
			<input type="submit" class="btn btn-secondary" value="Search" />
        </p>
    </form>
	@foreach (var item in Model.Movie)
	{
		<div class="flex-container">
			<div class="card movie_card">
				<img src="@item.Poster" class="card-img-top" alt="@item.Title">
				<div class="card-body">
					<i class="fas fa-play play_button" data-toggle="tooltip" data-placement="bottom" title="Play Trailer"></i>
					<h5 class="card-title justify-content-around">@item.Title</h5>
					<span class="movie_info">@item.Year</span>
					<span class="movie_info float-right"><i class="fa-brands fa-imdb"></i>@item.imdbRating</span>
					<form method="post">
						<input type="submit" class="btn btn-secondary" value="Add to Watchlist" />
					</form>
				</div>
			</div>
			<div>
				<h3 class="text-light">@item.Title ( @item.Year )</h3>
				<p class="movie-info text-light">
					Plot: @item.Plot
				</p>
				<p class="movie-info text-light">
					Genre: @item.Genre
				</p>
				<p class="movie-info text-light">
					Runtime: @item.Runtime
				</p>
				<p class="movie-info text-light">
					Writer: @item.Writer
				</p>
			</div>
        </div>
	}
	
</div>
    

Pages/Movies/Index.cshtml
@page
@model IndexModel
@{
}
<h1>Add a movie to your Watchlist</h1>

<form>
    <p>
        Search: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Submit" />
    </p>
</form>
<form method="post">
    <input type="submit">
</form>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheWatchlist</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/8cafc277ac.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheWatchlist.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-gradient border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TheWatchlist</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer bg-black bg-opacity-50 text-light">
        <div class="container">
            &copy; @DateTime.Now.Year - The Watchlist - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>